### PR TITLE
WIP Implement fixed functionality in all designers

### LINKED ISSUE #231: Character arguments of length 1L need to be specified within `c()`
Current `construct_design_code()` function returns error when factorial `outcome_name = "Y"`, and only works when value provided as `outcome_name = c("Y")` because of the way the function pastes strings.

### PR DESCRIPTION
**Pull request by clabima**
### Description

Implements fixed functionality in all designers using combination of `glue::glue()` and `substitute()` approaches. Note:

*  This approach does not affect the source code of any designers. Arguments passed onto `args_to_fix` are replaced for their values inside the `construct_design_code()` function.
* As it is now, all assignments in the body of the designer function need to be separated by new line, as a way of flagging unique expressions in the code string vector. Any suggestions for how to remove this restriction are welcome.
* Closes #231

### Checklist
- [X] Branch is passing devtools::check() with 0 errors, warnings, or notes

### CODE REVIEW

**Comment by jaspercooper** [comment]
Wow, this looks pretty amazing. And really really nice that you don't have to change the source code into rlang salad. Thanks for the work on this! 

@nfultz would be great to get your take on this.

Small thing that has been bugging me: the argument "fixed" doesn't seem expressive enough, and has connotations with other things (effects, issues, breakages). What we're trying to say is "these are the arguments will not be output as variables in the code, but will be *fixed* at the value provided when the design is declared," right?

So I think we could have something like "fixed_arguments" or "constants." @macartan any thoughts? 

@clabima would you mind updating `news.md` with a description of the work in this PR? don't want to misrepresent it in the eventual release.

File: R/helpers.R [hunk 1]
```diff
@@ -77,20 +120,80 @@ construct_design_code <- function(designer, args, arguments_as_values = FALSE, e
...
+  #if any arguments are set to fixed
+  if(!is.null(fixed)){
+    #list of fixed arguments
+    list_fixed <- lapply(fixed, function(w) args[[w]])
+    names(list_fixed) <- fixed
+    # create string of list of fixed arguments
+    # there may be a neater way of turning list to string without structure wrap
+    list_fixed_str <- expr_text(expr(!!list_fixed))
+    list_fixed_str <- gsub("structure(", "", list_fixed_str, fixed = TRUE)
+    list_fixed_str <- gsub(", \\.Names =.+((\n)|.)+", "", list_fixed_str, perl = TRUE)
```
Comment (nfultz) [inline R/helpers.R]: Do you actually want gsub for these? consider anchoring using `^`/`$`

File: R/helpers.R [hunk 2]
```diff
@@ -77,20 +120,80 @@ construct_design_code <- function(designer, args, arguments_as_values = FALSE, e
...
+  expr_i <- group_code_lines(code)
+
+  #if any arguments are set to fixed
+  if(!is.null(fixed)){
+    #list of fixed arguments
+    list_fixed <- lapply(fixed, function(w) args[[w]])
+    names(list_fixed) <- fixed
+    # create string of list of fixed arguments
+    # there may be a neater way of turning list to string without structure wrap
+    list_fixed_str <- expr_text(expr(!!list_fixed))
```
Comment (nfultz) [inline R/helpers.R]: expr_text is just deparse - https://github.com/r-lib/rlang/blob/89449b730351f3f8d957fb67e672f145760e524b/R/expr.R#L220

File: R/helpers.R [hunk 3]
```diff
@@ -77,20 +120,80 @@ construct_design_code <- function(designer, args, arguments_as_values = FALSE, e
...
+    list_fixed_str <- gsub("structure(", "", list_fixed_str, fixed = TRUE)
+    list_fixed_str <- gsub(", \\.Names =.+((\n)|.)+", "", list_fixed_str, perl = TRUE)
+    # bundle code lines related to same function together
+    design_exprs <- lapply(expr_i, function(e) paste0(code[e], collapse = " "))
+    
+    # evaluate a parsed expression where we substitute fixed arguments 
+    # for their values
+    fixed_code_lines <- lapply(design_exprs, function(e){
+      e <- paste0("substitute({", e, "},", list_fixed_str, ")")
+      t_e <- expr_text(eval(parse_expr(e), envir = eval_envir))
```
Comment (nfultz) [inline R/helpers.R]: here you basically have

    deparse(eval(parse(paste(substitute({e}, list_fixed_str)))))

since deparse(parse(x)) => x , this feels like it could be simplified.

To start, I would extract the anonymous function:

    code_fixer <- function(e, list_fixed_str, eval_envir) {
       ...
    }

    fixed_code_lines <- lapply(design_exprs,  code_fixer, list_fixed_str, eval_envir)

    and unit test  code_fixer extensively.

File: R/helpers.R [hunk 4]
```diff
@@ -77,20 +120,80 @@ construct_design_code <- function(designer, args, arguments_as_values = FALSE, e
...
+      gsub("^[{][\n]|[}]$", "", t_e)
+    })
+    
+    code_fixed <- code
+    for(i in 1:length(expr_i)){
```
Comment (nfultz) [inline R/helpers.R]: seq_along

File: R/helpers.R [hunk 5]
```diff
@@ -77,20 +120,80 @@ construct_design_code <- function(designer, args, arguments_as_values = FALSE, e
...
+      code_fixed[expr_i[[i]]] <- fixed_code_lines[[i]]
+    }
+    
+    code <- unique(code_fixed)
```
Comment (nfultz) [inline R/helpers.R]: ?

File: R/helpers.R [hunk 6]
```diff
@@ -77,20 +120,80 @@ construct_design_code <- function(designer, args, arguments_as_values = FALSE, e
...
+  }
+
+  # If `arguments_as_values = TRUE`, assignment code replaces argument symbol with its (evaluated) value
+  if(arguments_as_values && !is.null(args_eval)){
+    args_text <- sapply(1:length(args_eval), function(a){
+      # if the argument is of class character and length 1, keep quotation marks
+      # e.g., `name <- Y` is `name <- "Y"` 
+      if (length(args_eval[[a]]) == 1){
```
Comment (nfultz) [inline R/helpers.R]: I don't understand this logic - "if it's a character, then call as.character on it"

Also consider using the under-appreciated mapply - 

    args_text <- mapply(FUN = glue, arg_names, " < - ", args_eval)

File: R/helpers.R [hunk 7]
```diff
@@ -77,20 +120,80 @@ construct_design_code <- function(designer, args, arguments_as_values = FALSE, e
...
+        arg_quoted <- as.character(args_eval)[[a]]
+        glue({arg_names[a]}, " <- ", arg_quoted) 
+      }
+    })
+    
   } else {
-    # convert args to text
-    args_text <- as.character(sapply(names(args[2:length(args)]), function(x) paste0(x, " <- ", deparse(args[[x]]))))
+    # convert (unevaluated) args to text
+    args_text <- as.character(sapply(arg_names, function(x) paste0(x, " <- ", deparse(args[[x]]))))
```
Comment (nfultz) [inline R/helpers.R]: vapply

File: R/helpers.R [hunk 8]
```diff
@@ -140,3 +243,32 @@ clean_code <- function(code) {
...
+#' @importFrom rlang get_expr quo_text list2 quos
+#' @param code List contaitining design code.
+#' @param ... List of expressions to be substituted for their text.
+#' @return Code with expression text.
+sub_expr_text <- function(code, ...){
+  dots <- list2(...)
+  qdots <- quos(...)
+  exs <- sapply(1:length(dots), function(e) {
+    ex <- get_expr(qdots[[e]])
+    deparse(substitute(ex))
```
Comment (nfultz) [inline R/helpers.R]: This seems similarly indirect.

File: R/helpers.R [hunk 9]
```diff
@@ -140,3 +243,32 @@ clean_code <- function(code) {
...
+  })
+  
+  for(i in 1:length(dots)){
```
Comment (nfultz) [inline R/helpers.R]: mapply again.

File: R/helpers.R (hunk 5 above)
Comment (clabima) [reply R/helpers.R]: I got stuck in this. I wanted to go from `pre = c("a1", "a2", "a3", "b")` to `post = c("a1a2a3", "b")` using `expr_i <- list(c(1:3), 4)`. The simplest way I found is to replace `pre[1]`, `pre[2]`, and `pre[3]` with the same expression, hence `unique()`.

**Comment by jaspercooper** [comment]
@nfultz thanks so much for this thorough review and for the suggestions

**Comment by clabima** [comment]
Indeed! Working on them now.

Em qui, 28 de fev de 2019 às 12:45, Jasper Cooper <notifications@github.com>
escreveu:

File: R/helpers.R (hunk 6 above)
Comment (clabima) [reply R/helpers.R]: Indeed `mapply()` much better here, thanks!

At some point as.character() approach was successfully returning intended string `"name <- \"Y\""` instead of `"name <- Y"` but not working now. Will find a way to properly paste character vectors of lenght 1L without losing quotation marks.

File: R/helpers.R (hunk 2 above)
Comment (clabima) [reply R/helpers.R]: I like the built-in width argument, especially for the code creation. Replacing with `deparse(..., width.cutoff = 60L)`, but is there a specific reason for shying away from `rlang::expr_text()`?

File: R/helpers.R (hunk 1 above)
Comment (clabima) [reply R/helpers.R]: Created `str_within()` function that uses the anchoring you suggest, but also avoids the issue that regex seems to run into when using perl on a string containing "\n".

File: R/helpers.R (hunk 8 above)
Comment (clabima) [reply R/helpers.R]: Good point! I replaced with the following, which I think (hope) is the most direct possible:
```
    name_dots <- sapply(substitute(list(...))[-1], deparse)
```

File: R/helpers.R (hunk 9 above)
Comment (clabima) [reply R/helpers.R]: Because we need gsub to be iteratively applied to the same code object, keeping it as for loop.

**Comment by jaspercooper** [comment]
Thanks for these updates @clabima !

**Comment by clabima** [comment]
Sure! I think just missing news.md update and addressing the coverage issue. Will push these asap.

**Comment by clabima** [comment]
Should be ready to merge when checks go through. @jaspercooper @nfultz thank you for all the helpful feedback.

**Comment by jaspercooper** [comment]
Amazing work, thanks so much @clabima! and thanks to you @nfultz for the careful review and good ideas.
